### ISSUE TITLE
1.18.2: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)

### ISSUE THREAD

**Issue by Geethebluesky** [kb-1000/no-telemetry#9]
Getting this error on game start (single player):

java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.lang.Class.getMethod(Unknown Source) ~[?:?]
	at de.kb1000.notelemetry.NoTelemetryPreLaunch.onPreLaunch(NoTelemetryPreLaunch.java:22) ~[no-telemetry-1.3.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]

Am on MC 1.18.2, using Fabric Loader 0.14.8, Fabric API 0.57.0.

Let me know if you need my full logs. Thanks!

**Comment by kb-1000** [comment]
I did expect that to happen at some point. Which is why I catch that error and turn it into a warning, so it won't cause any crashes.
The code there is responsible for making it possible to mixin into (i.e. modify) Authlib, but as far as I know, now Fabric Loader makes that possible out-of-the-box so this should have zero effect. But I'll make a release removing that code and bumping the Loader dependency soon.

**Comment by kb-1000** [comment]
Fixed in 1.4.0
